### ISSUE TITLE
KD Implement Institutional Partner Program page

### ISSUE THREAD

**Issue by jessicatelles** [openstax/business-intel#146]
@jessicatelles commented on [Thu Oct 25 2018](https://github.com/openstax/bit-backlog/issues/33)

Trello: https://trello.com/c/PQxrTofr/259-osw2refresh09-design-institutional-partner-program-page

# Description

**What is being developed?**
A new web page for the Institutional Partner program.

**Who is the audience for this and what will they be able to do when it is released?**
The audience for this page consists of senior administrators at the institutional level, such as Chancellors, Presidents, Provosts, Vice Chancellors/Presidents of Academic Affairs; OER Coordinators; and Conference organizers. 

When this page is released, they will be able to get detailed information about the Institutional Partner program and its benefits, apply for the program when the application is open, and learn more about the resources OpenStax offers beyond our textbooks.

**Why do it?**
The Institutional Partner program has tremendous benefits for OpenStax. While it coaches institutions on how to adopt all kinds of OER, not just OpenStax, for their students, they are consistently some of our highest ranking schools in terms of adoptions and student savings. See latest IR report here. In addition, the program helps us develop strategic relationships at key institutions. 

**What are the contractual requirements, and/or potential opportunities, and/or risks to be averted?**
If we don’t continue to promote and expand the Institutional Partnership program, there is a risk that institutions will turn to Lumen Learning and other competitors for answers. We need somewhere for schools that are interested in increasing OER use to go for the answers and support they’re looking for. 

**When should it be released?**
Q1 2019

**Why should it be released then?**
We want institutions to have plenty of time to learn more about the program and determine if they should apply before the application opens in late spring 2019.

# Acceptance
- There is a page on OpenStax.org under the "What we do" section of the website. 
- The page is called "Institutional Partnerships"
- The page allows a user to download a brochure about the program.
- The page allows a user to sign up for more information about the program.
- The page allows a user to download an OER Summer Action Plan checklist and links to the Open Oregon Webinar hosted by Nicole. 
- The page contains the logos of current participants in the program, and a link expands to show the past participant logos.
- During the application season, the page has a button taking users to the Institutional Partnership application page.

# Epic Doc

https://docs.google.com/document/d/1P7lrNh7zSDXspphYA2AUyIMxXNdAB5tUkOxX6wus1XQ/edit#heading=h.wuc3pn1ckk21

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.
