### ISSUE TITLE
KD Optimize accounts flow

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/business-intel#223]
# Description
The Accounts flow needs to be updated in order to remove barriers to account creation, such as lost PIN emails or long flows, as well as address common customer complaints. We want to provide a better experience for our customers, help the Unified team reach their student account goals, and provide some relief to our Customer Support team.

# Acceptance Criteria
- We have identified a new solution to the PIN email problem and have incorporated into the new designs for faculty and student flows
- There is an updated visual design for faculty and student flows
- Faculty verification form is pulled out of Accounts and redirects to the adoption/interest forms when users reach that portion of the form
- Users see a popup letting them know they're instantly verified, in addition to receiving an email
- We have documented the new technical architecture of Accounts

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by victoria-cooke** [comment]
@meeragovindaraju points updated
