### ISSUE TITLE
Improve adoption data collection process

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#463]
# Description
Each year we send out emails to adopters asking them if they are still using our book. We want to improve this process by asking users to update their information when they log in or as they navigate the site. 
AM: User Story - https://docs.google.com/document/d/1cPMWmfu-ii-qf1nVFX4BNtEYo1PkivEKGHUU3ckRXEo/
AM: Past form: https://fs10.formsite.com/denverrice/form1/index.html?1535150252927
 
# Special requirements
- Adoption data for each user needs to be available to the FE from accounts or some other back end resource
# Acceptance Criteria
- When an adopting instructor *who has not updated their adoption information in the past 9 months* lands on openstax.org and is logged in, or when the adopting instructor logs in, they see a popup asking them to confirm their adoption information.
- If an instructor closes out and doesn't update their information, they will see the popup if they return after one week. (If they return within the week they will not see it again.)
- An instructor can close out of the screen without confirming their information.
- The instructor's name, email, book, and number of students is auto-populated by Salesforce.
- The instructor can edit the adoption information that's auto-populated.
- The instructor can add a new book.
- The instructor can indicate if they're no longer using an OpenStax book.
- When an instructor confirms their information, they see a second screen that asks them to fill out a user satisfaction survey, and offers a place for feedback or to submit a case report.
- If an instructor makes changes, their record is updated in Salesforce, and Salesforce indicates that the last updated date came from openstax.org.
- If an instructor records an adoption, it is updated in Salesforce and Salesforce indicates that the last updated date came from openstax.org. 
- The marketing team can see in Salesforce that the instructor updated their info from the website and suppress them from emails asking for the same thing. 

derive these from "Acceptance Criteria" during "Design" phase
# Acceptance Tests

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by andymuddimer** [comment]
LoFi of simple adoption data collection screens
https://drive.google.com/drive/folders/1Vy_h5Zp3h7tZ3ilnMu3GqLk9EwepsLeE

**Comment by allisonhowell** [comment]
@RoyEJohnson Could you take a look the lofi Andy added and we can discuss in detail tomorrow?

**Comment by andymuddimer** [comment]
Following Allison discussions with Roy and Michael, updated LoFi - 3
https://drive.google.com/drive/folders/1Vy_h5Zp3h7tZ3ilnMu3GqLk9EwepsLeE
