### ISSUE TITLE
Support Unified/REX for 2019-Q3

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#503]
# Description
Complete BIT work needed for REX release.

# Acceptance Criteria
- BIT work for REX release completed

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.
