### ISSUE TITLE
BIT - Release 2019-09-25

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#655]
Code freeze - QA: 09/13/2019 
RC Review meeting: 09/17/2019 
Code deploy - Staging: 09/19/2019
Code Release - Production: 09/25/2019

### Emergency Preparation 
- [x] Verify automated RDS backups completed successfully. 
- [x] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  none

###### Only list the repos that are deployed for this release. 

- [x] openstax/openstax-cms    c9171372a3eea6695e1765d42a9ed08d4674bde9
- [x] openstax/os-webview    86cc87289a49ffb86e7baffc557aa8620ee18226
- [x] openstax/oscms-deployment    8c1b9bfff1d48ca03a810e4ed0641e48133f57ee

#### Migrations
- [x] Yes  - openstax-cms
- [ ] No

#### After Deployment Tasks
- [ ]  none

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: 
###### Put an X for the repos *not* going out

- [ ] openstax/openstax-cms   c9171372a3eea6695e1765d42a9ed08d4674bde9
- [ ] openstax/os-webview    86cc87289a49ffb86e7baffc557aa8620ee18226
- [ ] openstax/oscms-deployment    8c1b9bfff1d48ca03a810e4ed0641e48133f57ee

-----------------------------------------------------------------------------------------

**Comment by scb6** [comment]
Existing SHAs: 
```
openstax/oscms-deployment @ baaeff09b5e1f0c0b1f18789650b8a778c16cd83
openstax/os-webview       @ 1dce2e3f4e5877ed8a9d27385353af86e07aba35
openstax/openstax-cms     @ ff93037b1768200a69ce61b5cd6abb93c769ec5a
```
