### ISSUE TITLE
BIT - Release 2019-10-09

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#689]
Code freeze - QA: 09/27/2019 
RC Review meeting: 10/01/2019
Code deploy - Staging: 10/03/2019
Code Release - Production: 10/09/2019 

### Approval
- [x] PDM approves deployment to staging environment

### Versions
- [ ] openstax/openstax-cms    f84bb0749cbb0c205cbc4120bb5d08dd1f9f9b50
- [ ] openstax/os-webview    2e12280304ffbd8af075be118b3e6199020f243c
- [ ] openstax/oscms-deployment    7f1b2698d45e91156953216bd2b4c979f9203cb6

## End Staging Deployment
-----------------------------------------------------------------------------------------
### Approval
- [ ] PDM approves deployment to production

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

### Before Deployment Tasks
- [ ]  task

#### Only list the repos that are deployed for this release. 

- [ ] openstax/openstax-cms    f84bb0749cbb0c205cbc4120bb5d08dd1f9f9b50
- [ ] openstax/os-webview    2e12280304ffbd8af075be118b3e6199020f243c
- [ ] openstax/oscms-deployment    7f1b2698d45e91156953216bd2b4c979f9203cb6

### Migrations
- [X] Yes 
- [ ] No 

### After Deployment Tasks
- [ ]  @mwharrison apply non-code fix for possible database upgrade issues for cms admin
- [ ]  @mwharrison to possibly run collectstatic after deployment

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End Production Deployment
-----------------------------------------------------------------------------------------

**Comment by Brooke-Fail** [comment]
All items tagged for this release have been verified in production. Closing this release.
